//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBracketManager.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public System.Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.Guid TeamId { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
